import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Sniglet } from "next/font/google";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CuteFont = Sniglet({
  subsets: ["latin"],
  weight: ["400", "800"],
  variable: "--font-sniglet",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${CuteFont.className}`}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
